import { mkdir, writeFile, chmod } from 'node:fs/promises';
import { join } from 'node:path';

const HOOK = `#!/usr/bin/env bash
# Auto-generated by Flavian init wizard.
# Runs the WooCommerce setup against the dev container after WP installs.
set -euo pipefail
cd "$(dirname "$0")/../../.."
./scripts/wordpress-install/setup-woocommerce.sh "$@"
`;

export async function setupWooCommerce(targetDir, config) {
  if (!config.woocommerce) return;
  if (config.themeStarter === 'flavian-shop') return;

  const dir = join(targetDir, 'scripts/wordpress-install/post-install.d');
  await mkdir(dir, { recursive: true });
  const hookPath = join(dir, '10-woocommerce.sh');
  await writeFile(hookPath, HOOK);
  await chmod(hookPath, 0o755);
}
