// Asset staging plan and WP-CLI seeding scripts.
//
// The generator works from the IR, which carries image references (hrefs), not
// bytes. So we compute a deterministic staged filename for every image frame and
// emit bin/import-media.sh to load whatever lands in assets/ into the media
// library. The CLI copies real bytes in when an asset source is available;
// reruns map the same frame to the same filename, so nothing churns.

import { assetFileName } from './slugs.js';

/**
 * @typedef {Object} PlannedAsset
 * @property {string} frameId
 * @property {string} name      Filename, e.g. "spread-1-image-1.jpg".
 * @property {string} relPath   Theme-relative path, e.g. "assets/spread-1-image-1.jpg".
 * @property {string} [href]    Original IR href.
 * @property {boolean} embedded Whether the bytes live inside the source IDML.
 *
 * Plan staged assets for every image frame across the spreads.
 * @param {import('../ir.js').DocumentIR} ir
 * @returns {{ assets: Array<PlannedAsset>, assetPathById: Map<string, string> }}
 */
export function planAssets(ir) {
	/** @type {Array<PlannedAsset>} */
	const assets = [];
	const assetPathById = new Map();

	(ir.spreads ?? []).forEach((spread, spreadIndex) => {
		let imageIndex = 0;
		for (const frame of spread.frames ?? []) {
			if (frame.kind !== 'image') continue;
			const name = assetFileName(spreadIndex, imageIndex, frame.href);
			imageIndex += 1;
			const relPath = `assets/${name}`;
			assets.push({
				frameId: frame.id,
				name,
				relPath,
				href: frame.href,
				embedded: Boolean(frame.embedded),
			});
			assetPathById.set(frame.id, relPath);
		}
	});

	return { assets, assetPathById };
}

/** bin/import-media.sh — import staged assets into the media library. */
export function buildImportScript() {
	return `#!/usr/bin/env bash
# Generated by @flavian/pipeline — seed the WordPress media library with the
# theme's staged assets. Paths resolve relative to the theme directory, so this
# runs from anywhere.
set -euo pipefail

THEME_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
ASSET_DIR="$THEME_DIR/assets"

if [ ! -d "$ASSET_DIR" ]; then
  echo "No assets directory at $ASSET_DIR — nothing to import." >&2
  exit 0
fi

shopt -s nullglob
imported=0
for asset in "$ASSET_DIR"/*; do
  echo "Importing $(basename "$asset")"
  wp media import "$asset" --title="$(basename "$asset")" --porcelain
  imported=$((imported + 1))
done
echo "Imported $imported asset(s)."
`;
}

/**
 * bin/seed-content.sh — create one draft page per spread, populated with that
 * spread's imported pattern. Only emitted when --seed-content is passed.
 *
 * @param {Array<{ title: string, slug: string }>} patterns
 */
export function buildSeedScript(patterns) {
	const lines = patterns.map(({ title, slug }) => {
		const safeTitle = String(title).replace(/'/g, "'\\''");
		return `wp post create --post_type=page --post_status=draft \\
  --post_title='${safeTitle}' \\
  --post_content='<!-- wp:pattern {"slug":"${slug}"} /-->' \\
  --porcelain`;
	});
	return `#!/usr/bin/env bash
# Generated by @flavian/pipeline — seed one draft page per imported InDesign
# spread, each populated with the spread's block pattern. Review and publish in
# wp-admin afterwards.
set -euo pipefail

${lines.join('\n\n')}

echo "Seeded ${patterns.length} draft page(s)."
`;
}
