// Theme bootstrap files: style.css (the theme header WordPress reads) and
// functions.php (registers the "InDesign Imports" pattern category, loads the
// text domain, enqueues the stylesheet). Both are deterministic — no version
// stamps or dates that would churn between runs.

import { phpSingleQuoted } from './escape.js';
import { PATTERN_CATEGORY } from './patterns.js';

/**
 * style.css with the WordPress theme header. The body is intentionally empty —
 * all design lives in theme.json — but the file must exist for the theme to
 * register.
 */
export function buildStyleCss({ name, slug, description, version = '0.1.0' }) {
	return [
		'/*',
		`Theme Name: ${name}`,
		'Theme URI: ',
		'Author: @flavian/pipeline',
		'Author URI: ',
		`Description: ${description}`,
		`Version: ${version}`,
		'Requires at least: 6.5',
		'Tested up to: 6.7',
		'Requires PHP: 7.4',
		'License: GNU General Public License v2 or later',
		'License URI: http://www.gnu.org/licenses/gpl-2.0.html',
		`Text Domain: ${slug}`,
		'Tags: full-site-editing, block-patterns, blog',
		'*/',
		'',
	].join('\n');
}

/**
 * functions.php: register the pattern category, load the text domain, enqueue
 * the (mostly empty) stylesheet. Prefixed with a slug-derived function prefix to
 * avoid collisions.
 */
export function buildFunctionsPhp({ name, slug, themePackage }) {
	const fnPrefix = slug.replace(/-/g, '_');
	const constName = `${slug.toUpperCase().replace(/-/g, '_')}_VERSION`;
	return `<?php
/**
 * ${phpSingleQuoted(name)} theme bootstrap.
 *
 * Generated by @flavian/pipeline (InDesign output generator).
 *
 * @package ${themePackage}
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! defined( '${constName}' ) ) {
	define( '${constName}', '0.1.0' );
}

/**
 * Theme setup.
 */
function ${fnPrefix}_setup() {
	load_theme_textdomain( '${slug}', get_template_directory() . '/languages' );
	add_theme_support( 'wp-block-styles' );
	add_theme_support( 'editor-styles' );
	add_theme_support( 'responsive-embeds' );
	add_theme_support( 'html5', array( 'search-form', 'gallery', 'caption', 'style', 'script' ) );
}
add_action( 'after_setup_theme', '${fnPrefix}_setup' );

/**
 * Register the block pattern category the imported spreads are filed under.
 *
 * @return void
 */
function ${fnPrefix}_register_pattern_categories() {
	if ( ! function_exists( 'register_block_pattern_category' ) ) {
		return;
	}
	register_block_pattern_category(
		'${PATTERN_CATEGORY}',
		array( 'label' => __( 'InDesign Imports', '${slug}' ) )
	);
}
add_action( 'init', '${fnPrefix}_register_pattern_categories' );

/**
 * Enqueue front-end styles.
 *
 * @return void
 */
function ${fnPrefix}_enqueue_assets() {
	wp_enqueue_style(
		'${slug}',
		get_stylesheet_uri(),
		array(),
		${constName}
	);
}
add_action( 'wp_enqueue_scripts', '${fnPrefix}_enqueue_assets' );
`;
}
